#!/usr/bin/env bash
set -e

# 'enabled' in currnet locale
ENABLED="enabled"

# get current uuid
CURRUUID=$(nmcli -f UUID,TYPE con show --active | grep wifi | awk '{print $1}')

# get wifi state
function wifistate() {
  echo "$(nmcli -fields WIFI g | sed -n 2p)"
}

# get active wifi connections
function wifiactive() {
  echo "$(nmcli con show --active | grep wifi)"
}

function if_wifistate() {
  # return a expression based on wifi state
  [[ "$(wifistate)" =~ $ENABLED ]] && rt=$1 || rt=$2
  echo $rt
}

function toggle_wifi() {
  toggle=$(if_wifistate "Disable Network" "Enable Network")
  echo $toggle
}

function current_connection() {
  currssid=$(iwgetid -r)
  [[ "$currssid" != '' ]] && currcon="Disconnect from $currssid" || currcon=""
  echo $currcon
}

function nmcli_list() {
  nmcli --fields SSID,SECURITY,BARS device wifi list
}

function menu() {
  wa=$(wifiactive)
  ws=$(wifistate)
  if [[ $ws =~ $ENABLED ]]; then
    if [[ "$wa" != '' ]]; then
      echo "$1\n\n$2\n$3\nManual Connection"
    else
      echo "$1\n\n$3\nManual Connection"
    fi
  else
    echo "$3"
  fi
}

function rofi_cmd() {
  # don't repeat lines with uniq -u
  echo -e "$1" | uniq -u | rofi -dmenu -i -p "Wi-Fi SSID" \
    -sorting-method fzf -sort -matching fuzzy
}

function rofi_menu() {
  TOGGLE=$(toggle_wifi)
  CURRCONNECT=$(current_connection)
  [[ "$TOGGLE" =~ 'Enable' ]] && LIST="" || LIST=$(nmcli_list)

  MENU=$(menu "$LIST" "$CURRCONNECT" "$TOGGLE")

  rofi_cmd "$MENU"
}

function get_ssid() {
  echo "$1" | awk '{print $1}'
}

function cleanup_networks() {
  nmcli --fields UUID,TIMESTAMP-REAL,DEVICE con show | grep -e '--' | awk '{print $1}' \
    | while read line; do nmcli con delete uuid $line; done
}

function main() {
  OPS=$(rofi_menu)
  CHSSID=$(get_ssid "$OPS")

  if [[ "$OPS" =~ 'Disable' ]]; then
    nmcli radio wifi off

  elif [[ "$OPS" =~ 'Enable' ]]; then
    nmcli radio wifi on

  elif [[ "$OPS" =~ 'Disconnect' ]]; then
    nmcli con down uuid $CURRUUID

  elif [[ "$OPS" =~ 'Manual' ]]; then
    # Manual entry of the SSID
    MSSID=$(echo -en "" | rofi -dmenu -p "SSID" -mesg "Enter the SSID of the network" \
      -lines 0)

    # manual entry of the PASSWORD
    MPASS=$(echo -en "" | rofi -dmenu -password -p "PASSWORD" -mesg \
      "Enter the PASSWORD of the network" -lines 0)

    # If the user entered a manual password, then use the password nmcli command
    if [ "$MPASS" = "" ]; then
      nmcli dev wifi con "$MSSID"
    elif [ "$MSSID" != '' ] && [ "$MPASS" != '' ]; then
      nmcli dev wifi con "$MSSID" password "$MPASS"
    fi

  else
    if [[ "$OPS" =~ "WPA2" ]] || [[ "$OPS" =~ "WEP" ]]; then
      WIFIPASS=$(echo -en "" | rofi -dmenu -password -p "PASSWORD" \
        -mesg "Enter the PASSWORD of the network" -lines 0)
    fi

    if [[ "$CHSSID" != '' ]] && [[ "$WIFIPASS" != '' ]]; then
      nmcli dev wifi con "$CHSSID" password "$WIFIPASS"
    fi
  fi
}

# clean up obsoleted connections
# nmcli --fields UUID,TIMESTAMP-REAL,DEVICE con show | grep never |  awk '{print $1}' | while read line; do nmcli con delete uuid $line; done

main
